apiVersion: "crd.jankovsky.me/v1"
kind: Animal
metadata:
  name: nala
spec:
  species: dog
  age: 6
  color: black
---
apiVersion: "crd.jankovsky.me/v1"
kind: Animal
metadata:
  name: frankie
spec:
  species: cat
  age: 10
  color: white
---
apiVersion: "crd.jankovsky.me/v1"
kind: Animal
metadata:
  name: jake
spec:
  species: dog
  age: 1
  color: golden
