apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: animals.crd.jankovsky.me
spec:
  group: crd.jankovsky.me
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                species:
                  type: string
                age:
                  type: integer
                color:
                  type: string
  scope: Namespaced
  names:
    plural: animals
    singular: animal
    kind: Animal
